Add Implication and Remove Nesting
QuMuLab/python-nnf pull request #27
Opened 2021-09-22 22:41 UTC by beckydvn

-Adds >> functionality to Var
-Creates an option to auto-simplify formulas upon creation by changing `auto_simplify` in the init module to True

2021-09-23 14:43 UTC, haz commented
This looks pretty good to me! Can you throw in some tests [here](https://github.com/QuMuLab/python-nnf/blob/master/test_nnf.py) to make sure things work (mainly useful for future regressions). Be sure to test multiple children in the left/right formula (e.g., `(x & y) & (w & z)`).

2021-09-23 15:44 UTC, blyxxyz requested changes
Tox/flake8 has some complaints about formatting, can you try to fix those? [`CONTRIBUTING.md`](https://github.com/QuMuLab/python-nnf/blob/master/CONTRIBUTING.md) has instructions for running it but let me know if it's unclear.

After you fix the formatting it might complain about Mypy, I left tips for that in the review.

2021-09-23 15:44 UTC, blyxxyz commented on nnf/__init__.py
> +            if type(self) == Or:
For some reason Mypy doesn't get it if you write it like this, this way should work:
```suggestion
            if isinstance(self, Or):
```
(that goes for all the other places with `type(...) == ...` too)

2021-09-23 15:44 UTC, blyxxyz commented on nnf/__init__.py
> +    def __rshift__(self: T_NNF, other: U_NNF)-> 'Or[t.Union[T_NNF.negate(), U_NNF]]':
Mypy doesn't understand this. I think I went a little overboard with the `T_NNF` and `U_NNF` in the other signatures, it makes things complicated for only minor benefit.

This works:
```suggestion
    def __rshift__(self, other: 'NNF')-> 'Or[NNF]':
```

2021-11-04 14:39 UTC, blyxxyz approved these changes
Looks good. Thank you for bearing with me.

2021-11-04 18:06 UTC, beckydvn commented
No worries, thanks for taking a look! Hope it proves to be useful in the long run :)

2021-11-23 16:32 UTC, haz approved these changes

2021-11-23 16:32 UTC, merged